version: '3.4'

services:

    nginx:
        container_name: nginx
        image: nginx:local
        build:
            context: .
            dockerfile: ./infrastructure/Dockerfile-prod
        ports:
            - '80:80'